{% set name = "ocean_data_gateway" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ocean_data_gateway-{{ version }}.tar.gz
  sha256: 96bb82e2177d57f338ab1a419bf993f4cca5039250d9d28c02fa6b30380fba24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - aiohttp
    - dask-core
    - erddapy
    - flake8
    - h5netcdf
    - intake
    - intake-xarray
    - ioos_qc
    - ipython
    - isort
    - joblib
    - jupyter
    - jupyterlab
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pint
    - pint-pandas
    - pint-xarray
    - pytest
    - python >=3.6
    - requests
    - scipy
    - shapely
    - xarray

test:
  imports:
    - ocean_data_gateway
    - ocean_data_gateway.readers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/ocean_data_gateway
  summary: Your gateway to ocean data.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
